version: "3.6"

services:
  javrater-client:
    container_name: javrater-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3005:3005"
